// Catalog content for the seed. Kept separate from seed.js so the copy is easy to
// edit without touching the seeding logic.

export const CATEGORIES = [
  "Jackets",
  "Denim",
  "Tops",
  "Dresses",
  "Bottoms",
  "Footwear",
  "Knitwear",
  "Accessories",
]

// Each listing is one physical garment, so the gallery is the set of shots our team
// takes of that single piece.
export const IMAGE_ANGLES = ["", "-back", "-detail", "-worn"]

export const PRODUCTS = [
  {
    seed: "windbreaker",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/windbreaker-front.jpg"],
    name: "Y2K Windbreaker",
    brand: "Nike ACG",
    category: "Jackets",
    gender: "unisex",
    price: 3499,
    originalPrice: 9999,
    sizes: ["S", "M", "L"],
    condition: "Like New",
    era: "Y2K",
    tag: "RARE FIND",
    rating: 4.8,
    reviewCount: 32,
    description:
      "A proper early-2000s ACG shell in the colourway everyone is hunting for. Lightweight ripstop with a packable hood, elasticated cuffs and the boxy cut that makes it sit right over a hoodie. Found in a Rotterdam warehouse lot and barely worn — the tags were still in the pocket.",
    highlights: [
      "Packable hood that tucks into the collar",
      "Water-repellent ripstop, taped seams intact",
      "Boxy Y2K cut — sizes up well for a layered look",
    ],
    details: {
      Material: "100% ripstop nylon, mesh lining",
      Fit: "Boxy / oversized",
      Colour: "Slate grey with volt trim",
      "Chest (flat)": '23" on size M',
      "Length (back)": '27" on size M',
      Care: "Cold machine wash, hang dry, no iron",
    },
    flaws: "None to note — closest thing to deadstock we've had in months.",
  },
  {
    seed: "carpenterjeans",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/carpenterjeans-front.jpg"],
    name: "Baggy Carpenter Denim",
    brand: "Dickies",
    category: "Denim",
    gender: "unisex",
    price: 2999,
    originalPrice: 6999,
    sizes: ["28", "30", "32", "34"],
    condition: "Good",
    era: "90s",
    tag: "NEW DROP",
    rating: 4.6,
    reviewCount: 58,
    description:
      "Genuine 90s Dickies carpenters with the hammer loop and double knee still fully intact. Heavy 14oz denim that has softened exactly where it should — behind the knees and at the seat — without going thin anywhere. Workwear that already did its work.",
    highlights: [
      "Original hammer loop and ruler pocket",
      "14oz denim, broken in but nowhere near worn through",
      "True 90s baggy leg — stacks over boots",
    ],
    details: {
      Material: "100% cotton, 14oz denim",
      Fit: "Relaxed / baggy straight leg",
      Colour: "Mid indigo, natural fade",
      Inseam: '32"',
      "Rise (front)": '12"',
      Care: "Cold wash inside out, line dry",
    },
    flaws: "Light fraying at the left hem and honest fading at the seat. No holes.",
  },
  {
    seed: "graphictee",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/graphictee-front.jpg"],
    name: "Cropped Graphic Tee",
    brand: "Vintage Band Tee",
    category: "Tops",
    gender: "women",
    price: 1799,
    originalPrice: 3799,
    sizes: ["XS", "S", "M"],
    condition: "Good",
    era: "2000s",
    tag: "ONE OF ONE",
    rating: 4.7,
    reviewCount: 41,
    description:
      "An original tour tee that a previous owner cropped by hand somewhere along the way — the raw edge has rolled and softened into something you genuinely can't buy new. Print is cracked in that way reproductions always fail to fake.",
    highlights: [
      "Hand-cropped raw hem, already rolled and settled",
      "Original screen print with authentic cracking",
      "Single-stitch sleeves — a real period detail",
    ],
    details: {
      Material: "100% cotton jersey, lightweight",
      Fit: "Cropped, close through the body",
      Colour: "Washed black",
      "Chest (flat)": '18" on size S',
      "Length (front)": '16" on size S',
      Care: "Cold wash inside out, hang dry — protect the print",
    },
    flaws: "Print cracking throughout (part of the appeal) and a faint mark near the left hem.",
  },
  {
    seed: "slipdress",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/slipdress-front.webp"],
    name: "Slip Satin Mini Dress",
    brand: "Bebe",
    category: "Dresses",
    gender: "women",
    price: 2299,
    originalPrice: 5799,
    sizes: ["XS", "S", "M", "L"],
    condition: "Like New",
    era: "Y2K",
    tag: "TRENDING",
    rating: 4.9,
    reviewCount: 27,
    description:
      "The exact bias-cut Bebe slip that keeps resurfacing on everyone's moodboard. Adjustable straps, a proper bias cut that skims rather than clings, and satin that still has its full sheen. Someone bought this for one night out and hung it up ever since.",
    highlights: [
      "True bias cut — hangs instead of gripping",
      "Adjustable straps with original sliders",
      "Satin sheen fully intact, no dulling",
    ],
    details: {
      Material: "Polyester satin, unlined",
      Fit: "Bias cut, skims the body",
      Colour: "Champagne",
      "Bust (flat)": '16.5" on size S',
      Length: '34" shoulder to hem',
      Care: "Hand wash cold or dry clean, hang to dry",
    },
    flaws: "None found. Straps, seams and hem all sound.",
  },
  {
    seed: "flannel",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/flannel-front.jpg"],
    name: "Oversized Flannel Shirt",
    brand: "Carhartt",
    category: "Tops",
    gender: "unisex",
    price: 1999,
    originalPrice: 4999,
    sizes: ["M", "L", "XL"],
    condition: "Good",
    era: "90s",
    tag: null,
    rating: 4.5,
    reviewCount: 19,
    description:
      "Heavyweight Carhartt flannel that has been washed enough times to go genuinely soft without losing any structure. Works as a shirt, works better as a light jacket over a tee. The kind of piece that quietly becomes the one you reach for.",
    highlights: [
      "Heavyweight brushed cotton, washed soft",
      "All original branded buttons present",
      "Roomy enough to layer over a hoodie",
    ],
    details: {
      Material: "100% brushed cotton flannel",
      Fit: "Oversized, drop shoulder",
      Colour: "Rust and forest plaid",
      "Chest (flat)": '25" on size L',
      "Length (back)": '30" on size L',
      Care: "Warm machine wash, tumble low",
    },
    flaws: "Slight collar fade and one replaced button at the cuff — matched closely.",
  },
  {
    seed: "platformsneakers",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/platformsneakers-front.jpg"],
    name: "Chunky Platform Sneakers",
    brand: "Buffalo",
    category: "Footwear",
    gender: "women",
    price: 4499,
    originalPrice: 11499,
    sizes: ["6", "7", "8", "9"],
    condition: "Like New",
    era: "Y2K",
    tag: "RARE FIND",
    rating: 4.8,
    reviewCount: 63,
    description:
      "The Buffalo platform in its original chunky silhouette — the one every current brand is busy reissuing at four times the price. Soles are clean, uppers hold their shape, and there is no yellowing anywhere on the midsole.",
    highlights: [
      'Original 2" platform sole, no compression',
      "Midsole still white — zero yellowing",
      "Barely-there tread wear",
    ],
    details: {
      Material: "Leather upper, rubber platform sole",
      Fit: "True to size, roomy toe box",
      Colour: "White with silver panel",
      "Platform height": '2"',
      Closure: "Lace-up, original laces",
      Care: "Wipe clean, avoid soaking the midsole",
    },
    flaws: "Faint scuff on the right toe cap, only visible up close.",
  },
  {
    seed: "trenchcoat",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/trenchcoat-front.jpg"],
    name: "Leather Trench Coat",
    brand: "Vintage",
    category: "Jackets",
    gender: "unisex",
    price: 5499,
    originalPrice: 14999,
    sizes: ["S", "M", "L"],
    condition: "Good",
    era: "80s",
    tag: "ONE OF ONE",
    rating: 4.9,
    reviewCount: 14,
    description:
      "Full-length 80s leather trench with the shoulder line and sweeping hem that define the era. The leather has developed a genuine patina — soft, slightly uneven, warm in tone. Heavy in the way real leather should be. This is the only one we have.",
    highlights: [
      "Full-grain leather with 40 years of real patina",
      "Belted waist with original buckle",
      "Fully lined, all seams sound",
    ],
    details: {
      Material: "Full-grain leather, satin lining",
      Fit: "Straight, dramatic shoulder",
      Colour: "Oxblood brown",
      "Chest (flat)": '22" on size M',
      Length: '48" shoulder to hem',
      Care: "Leather conditioner twice a year, never machine wash",
    },
    flaws:
      "Patina and softening throughout, one small scuff at the right elbow. Lining intact.",
  },
  {
    seed: "cargopants",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/cargopants-front.webp"],
    name: "Low-Rise Cargo Pants",
    brand: "Dickies",
    category: "Bottoms",
    gender: "women",
    price: 2799,
    originalPrice: 6299,
    sizes: ["S", "M", "L"],
    condition: "Good",
    era: "Y2K",
    tag: "NEW DROP",
    rating: 4.6,
    reviewCount: 48,
    description:
      "Low-rise cargos with the deep side pockets and slightly flared ankle that put them firmly in the early 2000s. Cotton twill that has gone soft with wear but still holds a shape. Every pocket, snap and drawcord works.",
    highlights: [
      "Six functional pockets, all snaps working",
      "Adjustable ankle drawcords intact",
      "True low rise — sits on the hip",
    ],
    details: {
      Material: "Cotton twill with a little stretch",
      Fit: "Low rise, relaxed leg",
      Colour: "Khaki",
      Inseam: '31"',
      "Rise (front)": '8"',
      Care: "Cold machine wash, tumble low",
    },
    flaws: "General softening and a faint mark on the right thigh pocket.",
  },
  {
    seed: "truckerjacket",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/truckerjacket-front.jpg"],
    name: "Denim Trucker Jacket",
    brand: "Levi's",
    category: "Jackets",
    gender: "men",
    price: 3799,
    originalPrice: 7999,
    sizes: ["S", "M", "L", "XL"],
    condition: "Like New",
    era: "90s",
    tag: "TRENDING",
    rating: 4.7,
    reviewCount: 71,
    description:
      "The Levi's trucker, which is to say the jacket every other denim jacket is copying. This one is a 90s make with the red tab intact and a light, even fade that you simply cannot rush. Goes with everything already in your wardrobe.",
    highlights: [
      "Original red tab and branded shank buttons",
      "Even, natural fade — no artificial distressing",
      "Classic cropped trucker length",
    ],
    details: {
      Material: "100% cotton denim, 12oz",
      Fit: "Regular, cropped at the waist",
      Colour: "Mid stonewash",
      "Chest (flat)": '21" on size M',
      "Length (back)": '24" on size M',
      Care: "Cold wash inside out, line dry",
    },
    flaws: "Nothing structural. Gentle whiskering at the cuffs and a soft collar.",
  },
  {
    seed: "pleatedskirt",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/pleatedskirt-front.png"],
    name: "Pleated Mini Skirt",
    brand: "Vintage Plaid",
    category: "Bottoms",
    gender: "women",
    price: 1699,
    originalPrice: 3999,
    sizes: ["XS", "S", "M"],
    condition: "Good",
    era: "90s",
    tag: null,
    rating: 4.4,
    reviewCount: 22,
    description:
      "Proper pressed-pleat plaid mini with a side zip and a wool-blend weight that makes the pleats actually hold. Not the flimsy polyester version — this one swings correctly when you walk.",
    highlights: [
      "Wool blend, pleats hold their press",
      "Concealed side zip with hook and eye",
      "Fully lined so it never clings",
    ],
    details: {
      Material: "Wool blend, polyester lining",
      Fit: "High waist, A-line",
      Colour: "Green and navy plaid",
      "Waist (flat)": '13" on size S',
      Length: '15" from waist',
      Care: "Dry clean, cool iron on the reverse",
    },
    flaws: "Two pleats need re-pressing after shipping. Lining has a small repaired seam.",
  },
  {
    seed: "beadednecklace",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/beadednecklace-front.webp"],
    name: "Beaded Statement Necklace",
    brand: "Handmade Vintage",
    category: "Accessories",
    gender: "women",
    price: 1199,
    originalPrice: 2499,
    sizes: ["One Size"],
    condition: "Like New",
    era: "Y2K",
    tag: "ONE OF ONE",
    rating: 4.9,
    reviewCount: 9,
    description:
      "Hand-strung glass beads in a graduated pattern that someone clearly took real time over. Restrung by us on fresh wire so it will not scatter across your floor. Genuinely a single object — there is no second one of these anywhere.",
    highlights: [
      "Hand-strung glass beads, graduated pattern",
      "Professionally restrung on new wire",
      "Lobster clasp replaced with a new one",
    ],
    details: {
      Material: "Glass beads, stainless wire and clasp",
      Length: '18" with a 2" extender',
      Colour: "Amber, jade and clear",
      "Bead size": "6-12mm graduated",
      Care: "Store flat, keep away from perfume",
    },
    flaws: "None — restrung and checked bead by bead before listing.",
  },
  {
    seed: "buckethat",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/buckethat-front.jpg"],
    name: "Retro Bucket Hat",
    brand: "Kangol",
    category: "Accessories",
    gender: "unisex",
    price: 1349,
    originalPrice: 2899,
    sizes: ["One Size"],
    condition: "Good",
    era: "90s",
    tag: null,
    rating: 4.5,
    reviewCount: 26,
    description:
      "Kangol bucket in the towelling fabric that made them famous, with the kangaroo logo still crisp on the back. Brim holds its shape and the interior band is clean. Reliable, unfussy, works with everything.",
    highlights: [
      "Original embroidered kangaroo logo",
      "Towelling fabric, brim holds its shape",
      "Interior sweatband clean and intact",
    ],
    details: {
      Material: "Cotton blend towelling",
      Fit: 'One size, 22-23" circumference',
      Colour: "Faded navy",
      "Brim width": '2"',
      Care: "Hand wash cold, air dry on a form",
    },
    flaws: "Very light fading on the crown from sun. Nothing structural.",
  },
  {
    seed: "leatherbiker",
    images: ["https://images.unsplash.com/photo-1551028719-00167b16eac5?w=900&h=1125&fit=crop&q=80"],
    name: "Black Leather Biker Jacket",
    brand: "Schott NYC",
    gender: "unisex",
    category: "Jackets",
    price: 8499,
    originalPrice: 21999,
    sizes: ["S", "M", "L"],
    condition: "Good",
    era: "90s",
    tag: "GRAILS",
    description:
      "A proper asymmetric-zip biker in heavy black cowhide. The leather has softened exactly where it should - elbows, collar, the fold at the waist - and taken on the low shine that only comes from years of wear. Silver hardware runs clean, and every zip pulls smoothly.",
    highlights: [
      "Heavyweight cowhide with a broken-in drape",
      "Asymmetric zip, all hardware working",
      "Quilted lining intact at the shoulders",
    ],
    details: {
      "Material": "100% cowhide leather, polyester lining",
      "Fit": "True to size, slim through the body",
      "Colour": "Black",
      "Chest (flat)": "21 in on size M",
      "Care": "Leather conditioner twice a year",
    },
    flaws: "Light surface scuffing on the left cuff and a faint crease across the back - consistent with age, nothing structural.",
  },
  {
    seed: "tanleather",
    images: ["https://images.unsplash.com/photo-1623854156816-4c4fc355ffc7?w=900&h=1125&fit=crop&q=80"],
    name: "Tan Leather Jacket",
    brand: "Vintage",
    gender: "unisex",
    category: "Jackets",
    price: 6299,
    originalPrice: 15999,
    sizes: ["M", "L"],
    condition: "Good",
    era: "80s",
    tag: null,
    description:
      "Warm cognac-brown leather with a relaxed, slightly boxy cut. The colour has faded unevenly across the shoulders in the way good leather does, going lighter where the sun caught it. Sits somewhere between a bomber and a blouson.",
    highlights: [
      "Rich cognac patina, lighter at the shoulders",
      "Relaxed 80s cut - layers over knitwear",
      "Two front pockets, both lined",
    ],
    details: {
      "Material": "Full-grain leather",
      "Fit": "Relaxed / boxy",
      "Colour": "Cognac brown",
      "Care": "Wipe clean, condition annually",
    },
    flaws: "Colour is genuinely uneven - that is the appeal, but worth knowing if you want uniform.",
  },
  {
    seed: "rustbomber",
    images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900&h=1125&fit=crop&q=80"],
    name: "Rust Bomber Jacket",
    brand: "Uniqlo",
    gender: "unisex",
    category: "Jackets",
    price: 2299,
    originalPrice: 5499,
    sizes: ["S", "M", "L"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "A clean terracotta bomber with ribbed collar, cuffs and hem. Lightweight enough for evenings rather than winter, and the colour is far nicer in person than most photos manage - a soft burnt orange rather than anything loud.",
    highlights: [
      "Ribbed knit collar, cuffs and hem",
      "Lightweight shell - a three-season jacket",
      "Zip pocket on the left sleeve",
    ],
    details: {
      "Material": "Recycled polyester shell and lining",
      "Fit": "Regular",
      "Colour": "Rust / terracotta",
      "Care": "Machine wash cold, hang dry",
    },
    flaws: "None - worn a handful of times at most.",
  },
  {
    seed: "pufferjacket",
    images: ["https://images.unsplash.com/photo-1706765779494-2705542ebe74?w=900&h=1125&fit=crop&q=80"],
    name: "Quilted Down Puffer",
    brand: "Superdry",
    gender: "unisex",
    category: "Jackets",
    price: 4199,
    originalPrice: 11999,
    sizes: ["M", "L", "XL"],
    condition: "Good",
    era: "Y2K",
    tag: "WARMEST",
    description:
      "A proper horizontal-baffle down puffer with a high funnel collar. Loft is still strong through the chest and arms, which is the thing that actually matters on a secondhand puffer - plenty of them arrive flat and sad. This one has not.",
    highlights: [
      "Down fill with loft still intact",
      "High funnel collar, zips to the chin",
      "Deep hand pockets, both lined in fleece",
    ],
    details: {
      "Material": "Nylon shell, down/feather fill",
      "Fit": "Regular, room for a knit underneath",
      "Colour": "Off-white",
      "Care": "Down-specific wash, tumble with dryer balls",
    },
    flaws: "One tiny repaired pinhole on the lower right baffle - no feather loss.",
  },
  {
    seed: "momjeans",
    images: ["https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?w=900&h=1125&fit=crop&q=80"],
    name: "Light Wash Mom Jeans",
    brand: "Levi's",
    gender: "women",
    category: "Denim",
    price: 2799,
    originalPrice: 6499,
    sizes: ["26", "28", "30"],
    condition: "Good",
    era: "90s",
    tag: "BESTSELLER",
    description:
      "High-rise, tapered, light indigo - the cut everyone actually means when they say mom jeans. Rigid cotton that has gone soft with washing but still holds its shape at the waistband and seat.",
    highlights: [
      "True high rise, sits on the natural waist",
      "Softened rigid denim, no stretch",
      "Original button fly and rivets",
    ],
    details: {
      "Material": "100% cotton denim",
      "Fit": "High rise, tapered leg",
      "Colour": "Light indigo",
      "Waist (flat)": "14 in on size 28",
      "Inseam": "28 in",
      "Care": "Cold wash inside out",
    },
    flaws: "Light fading at the back pockets and a small fray at the left hem.",
  },
  {
    seed: "blackjeans",
    images: ["https://images.unsplash.com/photo-1718252540617-6ecda2b56b57?w=900&h=1125&fit=crop&q=80"],
    name: "Black Straight-Leg Jeans",
    brand: "Nudie Jeans",
    gender: "unisex",
    category: "Denim",
    price: 3199,
    originalPrice: 8999,
    sizes: ["30", "32", "34"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "Clean black denim in a straight leg, cuffed at the hem. Barely faded, which for black denim is genuinely rare secondhand - most of it arrives grey. Organic cotton, made to be worn hard.",
    highlights: [
      "Deep black with almost no fade",
      "Straight leg, cuffs neatly",
      "Organic cotton, selvedge hem",
    ],
    details: {
      "Material": "100% organic cotton",
      "Fit": "Mid rise, straight leg",
      "Colour": "Black",
      "Inseam": "32 in",
      "Care": "Wash rarely, cold, inside out",
    },
    flaws: "None to note.",
  },
  {
    seed: "denimshorts",
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=900&h=1125&fit=crop&q=80"],
    name: "Distressed Denim Shorts",
    brand: "Vintage",
    gender: "women",
    category: "Denim",
    price: 1499,
    originalPrice: 3999,
    sizes: ["26", "28", "30"],
    condition: "Good",
    era: "Y2K",
    tag: null,
    description:
      "High-waisted light-wash shorts with genuine distressing across the thighs - abraded rather than cut, so the threads still hold. Turned-up cuff that stays put without pinning.",
    highlights: [
      "High waist with a turned-up cuff",
      "Authentic abrasion, not scissor-cut",
      "Five-pocket with original hardware",
    ],
    details: {
      "Material": "100% cotton denim",
      "Fit": "High rise",
      "Colour": "Light wash",
      "Care": "Cold wash, hang dry",
    },
    flaws: "The distressing is real wear and will keep developing - expect the thigh holes to open slightly over time.",
  },
  {
    seed: "blackhoodie",
    images: ["https://plus.unsplash.com/premium_photo-1673356301340-4522591be5f7?w=900&h=1125&fit=crop&q=80"],
    name: "Heavyweight Black Hoodie",
    brand: "Champion",
    gender: "unisex",
    category: "Tops",
    price: 1999,
    originalPrice: 4999,
    sizes: ["S", "M", "L", "XL"],
    condition: "Good",
    era: "00s",
    tag: null,
    description:
      "Dense loopback cotton with a proper double-layer hood and a kangaroo pocket that has not stretched out. The kind of hoodie that gets heavier and better the more it is washed.",
    highlights: [
      "Heavyweight loopback cotton",
      "Double-layer hood, flat drawcords",
      "Ribbing still tight at cuffs and hem",
    ],
    details: {
      "Material": "80% cotton, 20% polyester",
      "Fit": "Regular",
      "Colour": "Black",
      "Care": "Wash cold, dry flat",
    },
    flaws: "Slight overall fade from black towards charcoal - even, not patchy.",
  },
  {
    seed: "whitecrewneck",
    images: ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=900&h=1125&fit=crop&q=80"],
    name: "White Crewneck Sweatshirt",
    brand: "Uniqlo",
    gender: "unisex",
    category: "Tops",
    price: 1299,
    originalPrice: 2999,
    sizes: ["S", "M", "L"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "A plain white crewneck with no branding anywhere on it, which is harder to find than it sounds. Brushed inside, smooth outside, and still properly white rather than the yellowed cream most secondhand whites turn.",
    highlights: [
      "Completely unbranded",
      "Brushed fleece interior",
      "Still genuinely white, no yellowing",
    ],
    details: {
      "Material": "Cotton-blend fleece",
      "Fit": "Regular",
      "Colour": "White",
      "Care": "Wash with whites, cold",
    },
    flaws: "None.",
  },
  {
    seed: "satinshirt",
    images: ["https://images.unsplash.com/photo-1612889002991-fbfaf775d231?w=900&h=1125&fit=crop&q=80"],
    name: "Champagne Satin Shirt",
    brand: "Vintage",
    gender: "women",
    category: "Tops",
    price: 1899,
    originalPrice: 4599,
    sizes: ["S", "M"],
    condition: "Like New",
    era: "90s",
    tag: "ONE OF ONE",
    description:
      "A liquid-drape satin shirt in warm champagne gold, cut long enough to tuck or wear loose. Catches light beautifully and creases far less than real silk. Mother-of-pearl buttons all present.",
    highlights: [
      "Fluid satin with a warm gold cast",
      "Mother-of-pearl buttons, none missing",
      "Long enough to tuck or leave out",
    ],
    details: {
      "Material": "Polyester satin",
      "Fit": "Relaxed",
      "Colour": "Champagne gold",
      "Care": "Hand wash cold, cool iron on reverse",
    },
    flaws: "None visible - no snags or pulls, which is the usual problem with satin.",
  },
  {
    seed: "stripedknit",
    images: ["https://images.unsplash.com/photo-1584030373081-f37b7bb4fa8e?w=900&h=1125&fit=crop&q=80"],
    name: "Striped Knit Top",
    brand: "COS",
    gender: "women",
    category: "Tops",
    price: 1599,
    originalPrice: 3899,
    sizes: ["XS", "S", "M"],
    condition: "Good",
    era: "Modern",
    tag: null,
    description:
      "Fine-gauge cream knit with narrow vertical stripes and a slightly dropped shoulder. Light enough for layering under a jacket without adding bulk.",
    highlights: [
      "Fine gauge - layers flat",
      "Dropped shoulder, relaxed sleeve",
      "Holds shape after washing",
    ],
    details: {
      "Material": "Cotton-viscose blend",
      "Fit": "Relaxed",
      "Colour": "Cream with grey stripe",
      "Care": "Cold wash, dry flat",
    },
    flaws: "Very slight pilling under the arms.",
  },
  {
    seed: "fairisle",
    images: ["https://images.unsplash.com/photo-1758981400268-1181291b9503?w=900&h=1125&fit=crop&q=80"],
    name: "Fair Isle Wool Cardigan",
    brand: "Vintage",
    gender: "unisex",
    category: "Knitwear",
    price: 3899,
    originalPrice: 9499,
    sizes: ["M", "L"],
    condition: "Good",
    era: "70s",
    tag: "RARE FIND",
    description:
      "A genuine Nordic-yoke cardigan in deep burgundy with a cream snowflake pattern across the shoulders. Real wool, properly heavy, with the faint lanolin smell that tells you it has not been chemically stripped.",
    highlights: [
      "Hand-knitted Nordic yoke pattern",
      "Undyed cream motif against burgundy",
      "Pewter-look buttons, all original",
    ],
    details: {
      "Material": "100% wool",
      "Fit": "Regular, generous through the body",
      "Colour": "Burgundy and cream",
      "Care": "Hand wash wool detergent, dry flat",
    },
    flaws: "Wool is slightly felted at the underarms from age. No moth damage - checked carefully.",
  },
  {
    seed: "chunkyknit",
    images: ["https://images.unsplash.com/photo-1574201635302-388dd92a4c3f?w=900&h=1125&fit=crop&q=80"],
    name: "Chunky Ribbed Knit Sweater",
    brand: "And Other Stories",
    gender: "women",
    category: "Knitwear",
    price: 2499,
    originalPrice: 6299,
    sizes: ["S", "M", "L"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "Oversized ivory rib-knit with balloon sleeves and a wide neck that sits off one shoulder if you let it. Substantial without being scratchy - the yarn has clearly been blended for softness.",
    highlights: [
      "Deep rib, oversized volume",
      "Balloon sleeve with a tight cuff",
      "Soft enough against bare skin",
    ],
    details: {
      "Material": "Wool-acrylic blend",
      "Fit": "Oversized",
      "Colour": "Ivory",
      "Care": "Hand wash, dry flat, do not hang",
    },
    flaws: "None - worn once or twice.",
  },
  {
    seed: "hightops",
    images: ["https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=900&h=1125&fit=crop&q=80"],
    name: "White Leather High-Tops",
    brand: "Nike",
    gender: "unisex",
    category: "Footwear",
    price: 4599,
    originalPrice: 10999,
    sizes: ["UK7", "UK8", "UK9"],
    condition: "Good",
    era: "Modern",
    tag: "BESTSELLER",
    description:
      "Classic white leather high-tops with the ankle strap intact and soles that still have real tread on them. Cleaned and deodorised before listing. Creasing across the toe box is present and honest.",
    highlights: [
      "Leather upper, cleaned and conditioned",
      "Tread still deep across the outsole",
      "Original laces plus a spare set",
    ],
    details: {
      "Material": "Leather upper, rubber outsole",
      "Fit": "True to size",
      "Colour": "White",
      "Care": "Wipe with a damp cloth, air dry",
    },
    flaws: "Toe box creasing on both shoes and a faint grey scuff on the right midsole.",
  },
  {
    seed: "brownboots",
    images: ["https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=900&h=1125&fit=crop&q=80"],
    name: "Brown Leather Lace-Up Boots",
    brand: "Dr. Martens",
    gender: "unisex",
    category: "Footwear",
    price: 5299,
    originalPrice: 13999,
    sizes: ["UK7", "UK8", "UK9", "UK10"],
    condition: "Good",
    era: "00s",
    tag: null,
    description:
      "Dark brown eight-eye leather boots, broken in but nowhere near worn out. The leather has darkened at the flex point across the toe, which is exactly what you want - they will mould to you rather than fight you.",
    highlights: [
      "Eight-eyelet lace-up, all hooks intact",
      "Goodyear-welted - resoleable",
      "Already broken in, no blister period",
    ],
    details: {
      "Material": "Leather upper, welted rubber sole",
      "Fit": "Runs half a size large",
      "Colour": "Dark brown",
      "Care": "Polish monthly",
    },
    flaws: "Heel edges worn slightly on the outside - normal gait wear, plenty of sole left.",
  },
  {
    seed: "chelseaboots",
    images: ["https://plus.unsplash.com/premium_photo-1729788891863-0d9b6f2b453b?w=900&h=1125&fit=crop&q=80"],
    name: "Black Chelsea Lug Boots",
    brand: "Vagabond",
    gender: "unisex",
    category: "Footwear",
    price: 4899,
    originalPrice: 11499,
    sizes: ["UK6", "UK7", "UK8"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "Smooth black leather Chelsea boots on a chunky lug sole. Elastic gussets are still tight - the usual failure point on secondhand Chelseas - and the pull tab has no fraying.",
    highlights: [
      "Elastic gussets still firm",
      "Heavy lug sole with deep grip",
      "Smooth leather, no creasing yet",
    ],
    details: {
      "Material": "Leather upper, rubber lug sole",
      "Fit": "True to size",
      "Colour": "Black",
      "Care": "Wipe clean, condition seasonally",
    },
    flaws: "None - soles barely marked.",
  },
  {
    seed: "woventote",
    images: ["https://images.unsplash.com/photo-1598532163257-ae3c6b2524b6?w=900&h=1125&fit=crop&q=80"],
    name: "Woven Leather Tote",
    brand: "Vintage",
    gender: "women",
    category: "Accessories",
    price: 3499,
    originalPrice: 8999,
    sizes: ["One Size"],
    condition: "Like New",
    era: "Modern",
    tag: "ONE OF ONE",
    description:
      "A wide basket-weave tote in warm cognac leather with a detachable gold chain. Big enough for a laptop, soft enough to fold under an arm. The weave has no loose strands anywhere.",
    highlights: [
      "Hand-woven cognac leather",
      "Detachable gold-tone chain strap",
      "Fits a 13-inch laptop",
    ],
    details: {
      "Material": "Woven leather, gold-tone hardware",
      "Dimensions": "15 x 10 x 4 in",
      "Colour": "Cognac",
      "Care": "Keep dry, condition lightly",
    },
    flaws: "None - interior is clean.",
  },
  {
    seed: "crossbodybag",
    images: ["https://images.unsplash.com/photo-1559563458-527698bf5295?w=900&h=1125&fit=crop&q=80"],
    name: "Studded Crossbody Bag",
    brand: "Vintage",
    gender: "women",
    category: "Accessories",
    price: 2899,
    originalPrice: 7499,
    sizes: ["One Size"],
    condition: "Good",
    era: "Y2K",
    tag: null,
    description:
      "A structured flap bag in pale dove grey with pyramid studs around the border and a gold chain strap. Holds its shape when empty, which is the mark of a properly built frame.",
    highlights: [
      "Pyramid studs, none missing",
      "Gold chain strap, shortens for shoulder wear",
      "Structured frame keeps its shape",
    ],
    details: {
      "Material": "Leather, gold-tone hardware",
      "Dimensions": "9 x 6 x 3 in",
      "Colour": "Dove grey",
      "Care": "Store stuffed to hold shape",
    },
    flaws: "Faint mark on the underside of the flap - only visible when open.",
  },
  {
    seed: "wayfarers",
    images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=900&h=1125&fit=crop&q=80"],
    name: "Black Wayfarer Sunglasses",
    brand: "Ray-Ban",
    gender: "unisex",
    category: "Accessories",
    price: 2199,
    originalPrice: 5999,
    sizes: ["One Size"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "The wayfarer shape in gloss black acetate. Lenses are clear of scratches under a torch, hinges are tight, and the arms fold without play. Comes with a generic hard case.",
    highlights: [
      "Scratch-free lenses, checked under light",
      "Hinges tight, no arm wobble",
      "Hard case included",
    ],
    details: {
      "Material": "Acetate frame",
      "Fit": "Standard width",
      "Colour": "Gloss black",
      "Care": "Microfibre only, never a shirt",
    },
    flaws: "None on the lenses. Very light surface marks on the inner arm where it meets the temple.",
  },
  {
    seed: "olivescarf",
    images: ["https://images.unsplash.com/photo-1643312892626-80632ef6d7dc?w=900&h=1125&fit=crop&q=80"],
    name: "Olive Wool Scarf",
    brand: "Vintage",
    gender: "unisex",
    category: "Accessories",
    price: 999,
    originalPrice: 2799,
    sizes: ["One Size"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "A large square wool-blend scarf in deep olive with a raw fringed edge. Big enough to work as a wrap rather than just a neck scarf, and light enough not to bulk out a coat collar.",
    highlights: [
      "Oversized square - wears as a wrap",
      "Raw fringed edge, no unravelling",
      "Lightweight for the size",
    ],
    details: {
      "Material": "Wool-viscose blend",
      "Dimensions": "51 x 51 in",
      "Colour": "Olive green",
      "Care": "Dry clean or gentle hand wash",
    },
    flaws: "None.",
  },
  {
    seed: "whitecap",
    images: ["https://plus.unsplash.com/premium_photo-1680859126205-1c593bb4f9e8?w=900&h=1125&fit=crop&q=80"],
    name: "White Baseball Cap",
    brand: "Unbranded",
    gender: "unisex",
    category: "Accessories",
    price: 899,
    originalPrice: 1999,
    sizes: ["One Size"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "A plain white six-panel cap with a curved brim and no logo of any kind. Adjustable strap at the back. The sweatband is clean, which is the first thing worth checking on any secondhand cap.",
    highlights: [
      "Completely unbranded, six-panel",
      "Pre-curved brim",
      "Clean sweatband, adjustable strap",
    ],
    details: {
      "Material": "Cotton twill",
      "Fit": "Adjustable",
      "Colour": "White",
      "Care": "Spot clean only, never machine wash",
    },
    flaws: "None.",
  },
  {
    seed: "tieredgown",
    images: ["https://images.unsplash.com/photo-1715852700550-6436320162e6?w=900&h=1125&fit=crop&q=80"],
    name: "Tiered Floral Gown",
    brand: "Vintage",
    gender: "women",
    category: "Dresses",
    price: 7499,
    originalPrice: 19999,
    sizes: ["S", "M"],
    condition: "Like New",
    era: "Modern",
    tag: "GRAILS",
    description:
      "A blush strapless gown with three embroidered tiers, each one carrying a different floral motif. Boned bodice that stays up without help. This is an occasion piece and photographs extraordinarily well.",
    highlights: [
      "Three embroidered tiers, each distinct",
      "Boned strapless bodice, internal grip tape",
      "Concealed back zip",
    ],
    details: {
      "Material": "Embroidered tulle over lining",
      "Fit": "Fitted bodice, full skirt",
      "Colour": "Blush with multicolour embroidery",
      "Care": "Dry clean only",
    },
    flaws: "None - appears to have been worn once.",
  },
  {
    seed: "sundress",
    images: ["https://images.unsplash.com/photo-1762154057377-cc9d3dd6900c?w=900&h=1125&fit=crop&q=80"],
    name: "Floral Midi Sundress",
    brand: "Zara",
    gender: "women",
    category: "Dresses",
    price: 2299,
    originalPrice: 5499,
    sizes: ["XS", "S", "M"],
    condition: "Good",
    era: "Modern",
    tag: null,
    description:
      "A white midi sundress printed with scattered florals, cut with a fitted bodice, thin straps and a full skirt that moves properly when you walk. Fully lined through the skirt.",
    highlights: [
      "Adjustable spaghetti straps",
      "Full circle skirt, fully lined",
      "Side zip with a hook-and-eye",
    ],
    details: {
      "Material": "Viscose",
      "Fit": "Fitted bodice, full skirt",
      "Colour": "White multi-floral",
      "Length": "44 in shoulder to hem",
      "Care": "Cold wash, hang dry",
    },
    flaws: "One strap has been shortened slightly - neatly done, barely visible.",
  },
  {
    seed: "wideleg",
    images: ["https://images.unsplash.com/photo-1493357335960-4583bfa6f8d9?w=900&h=1125&fit=crop&q=80"],
    name: "Grey Wide-Leg Trousers",
    brand: "COS",
    gender: "unisex",
    category: "Bottoms",
    price: 2699,
    originalPrice: 6999,
    sizes: ["28", "30", "32"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "Pleated wide-leg trousers in a soft grey wool blend, cut long enough to break over a shoe. The pleats are still sharp and the fabric has a dry, matte handle rather than anything shiny.",
    highlights: [
      "Double-pleated front, sharp crease",
      "Wide leg with a full-length break",
      "Side-adjuster tabs at the waist",
    ],
    details: {
      "Material": "Wool-blend suiting",
      "Fit": "High rise, wide leg",
      "Colour": "Grey",
      "Inseam": "31 in",
      "Care": "Dry clean",
    },
    flaws: "None.",
  },
  {
    seed: "khakiovershirt",
    images: ["https://images.unsplash.com/photo-1776838103951-993ff1ffc916?w=900&h=1125&fit=crop&q=80"],
    name: "Khaki Linen Overshirt",
    brand: "Uniqlo",
    gender: "men",
    category: "Tops",
    price: 1899,
    originalPrice: 4299,
    sizes: ["M", "L", "XL"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "A washed khaki linen overshirt cut to wear open over a tee or buttoned as a light jacket. Linen this soft only comes from real wear - it has lost the papery stiffness new linen has and gained a proper drape.",
    highlights: [
      "Pure linen, washed soft",
      "Chest pocket with a button flap",
      "Cut long enough to wear open",
    ],
    details: {
      "Material": "100% linen",
      "Fit": "Relaxed, boxy",
      "Colour": "Washed khaki",
      "Care": "Cold wash, line dry, iron damp",
    },
    flaws: "Natural linen slubs throughout - the weave, not damage.",
  },
  {
    seed: "whitepolo",
    images: ["https://plus.unsplash.com/premium_photo-1682165232152-874f4a56b4f5?w=900&h=1125&fit=crop&q=80"],
    name: "White Pique Polo",
    brand: "Fred Perry",
    gender: "men",
    category: "Tops",
    price: 1599,
    originalPrice: 3999,
    sizes: ["S", "M", "L"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "A clean white pique polo with a contrast tipped collar that still stands up properly - the first thing to go on a tired polo is the collar, and this one has not gone. Shown front and back so you can see both.",
    highlights: [
      "Collar still holds its shape",
      "Contrast tipping at collar and cuff",
      "Two-button placket, both original",
    ],
    details: {
      "Material": "Cotton pique",
      "Fit": "Regular",
      "Colour": "White with dark tipping",
      "Care": "Wash cold, hang to dry",
    },
    flaws: "None - no yellowing at the collar or underarms, which is rare on a white polo.",
  },
  {
    seed: "whitehenley",
    images: ["https://images.unsplash.com/photo-1713881604560-085594ed2c3d?w=900&h=1125&fit=crop&q=80"],
    name: "White Cotton Henley",
    brand: "Vintage",
    gender: "men",
    category: "Tops",
    price: 1199,
    originalPrice: 2799,
    sizes: ["S", "M", "L"],
    condition: "Good",
    era: "Modern",
    tag: null,
    description:
      "A short-sleeve henley in heavy white cotton with a three-button placket. Simple enough to disappear under anything and substantial enough to wear on its own.",
    highlights: [
      "Heavy cotton, not see-through",
      "Three-button placket",
      "Unbranded - no logos anywhere",
    ],
    details: {
      "Material": "100% cotton",
      "Fit": "Regular",
      "Colour": "White",
      "Care": "Wash with whites, cold",
    },
    flaws: "Very slight softening at the collar edge.",
  },
  {
    seed: "navycrew",
    images: ["https://images.unsplash.com/photo-1614975059251-992f11792b9f?w=900&h=1125&fit=crop&q=80"],
    name: "Navy Crewneck Sweatshirt",
    brand: "Carhartt",
    gender: "men",
    category: "Tops",
    price: 2199,
    originalPrice: 5299,
    sizes: ["M", "L", "XL"],
    condition: "Good",
    era: "00s",
    tag: null,
    description:
      "Deep navy loopback sweatshirt with a small embroidered chest mark. Ribbing at the cuffs and hem is still tight, which is the honest test of whether a secondhand sweatshirt has any life left.",
    highlights: [
      "Loopback cotton, brushed inside",
      "Ribbing still firm at cuffs and hem",
      "Small embroidered chest logo",
    ],
    details: {
      "Material": "Cotton-polyester loopback",
      "Fit": "Regular",
      "Colour": "Navy",
      "Care": "Cold wash, dry flat",
    },
    flaws: "Light pilling under the arms. Colour is even throughout.",
  },
  {
    seed: "varsityjacket",
    images: ["https://images.unsplash.com/photo-1771310961705-c8b34eddbe9e?w=900&h=1125&fit=crop&q=80"],
    name: "Brown Varsity Jacket",
    brand: "Vintage",
    gender: "men",
    category: "Jackets",
    price: 6899,
    originalPrice: 17999,
    sizes: ["L", "XL"],
    condition: "Good",
    era: "90s",
    tag: "GRAILS",
    description:
      "A proper letterman in chocolate wool with tan leather sleeves and the original chenille patches still stitched down. The leather has creased at the elbows exactly the way it should and the snaps all hold.",
    highlights: [
      "Wool body, real leather sleeves",
      "Original chenille patches, none lifting",
      "Every press stud still snaps shut",
    ],
    details: {
      "Material": "Wool body, leather sleeves, quilted lining",
      "Fit": "Boxy, true to size",
      "Colour": "Chocolate and tan",
      "Care": "Dry clean only",
    },
    flaws: "Elbow creasing on both sleeves and light wear on the leather cuffs - age, not damage.",
  },
  {
    seed: "camelovercoat",
    images: ["https://images.unsplash.com/photo-1619603364904-c0498317e145?w=900&h=1125&fit=crop&q=80"],
    name: "Camel Wool Overcoat",
    brand: "COS",
    gender: "men",
    category: "Jackets",
    price: 7499,
    originalPrice: 19999,
    sizes: ["M", "L"],
    condition: "Like New",
    era: "Modern",
    tag: "RARE FIND",
    description:
      "A single-breasted camel overcoat that falls just past the knee, in a wool blend heavy enough to hang properly instead of flapping. Notch lapel, three buttons, and a clean unbroken shoulder line.",
    highlights: [
      "Falls past the knee, holds its line",
      "Notch lapel, single-breasted",
      "Fully lined with an inside pocket",
    ],
    details: {
      "Material": "Wool-cashmere blend",
      "Fit": "Regular, layers over a knit",
      "Colour": "Camel",
      "Care": "Dry clean, brush after wearing",
    },
    flaws: "None - no pilling at the collar or cuffs.",
  },
  {
    seed: "bluesuitblazer",
    images: ["https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=900&h=1125&fit=crop&q=80"],
    name: "Royal Blue Suit Blazer",
    brand: "Zara",
    gender: "men",
    category: "Jackets",
    price: 3999,
    originalPrice: 10999,
    sizes: ["38", "40", "42"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "A sharp royal blue single-breasted blazer with a slim notch lapel and working cuff buttons. Bright enough to carry a whole outfit and cut close enough to wear without tailoring.",
    highlights: [
      "Slim notch lapel, two-button front",
      "Working cuff buttons",
      "Double vent at the back",
    ],
    details: {
      "Material": "Wool-blend suiting",
      "Fit": "Slim",
      "Colour": "Royal blue",
      "Care": "Dry clean",
    },
    flaws: "None. Trousers are not included - this is the jacket only.",
  },
  {
    seed: "blacktapered",
    images: ["https://images.unsplash.com/photo-1584865288642-42078afe6942?w=900&h=1125&fit=crop&q=80"],
    name: "Black Tapered Trousers",
    brand: "Uniqlo",
    gender: "men",
    category: "Bottoms",
    price: 1799,
    originalPrice: 3999,
    sizes: ["30", "32", "34"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "Black tapered trousers with a cropped ankle that sits just above the shoe. Smart enough for an office, plain enough for a tee and trainers.",
    highlights: [
      "Tapered through the leg, cropped hem",
      "Elasticated back for comfort",
      "Holds a crease without ironing",
    ],
    details: {
      "Material": "Polyester-rayon blend",
      "Fit": "Slim tapered",
      "Colour": "Black",
      "Inseam": "28 in",
      "Care": "Machine wash cold",
    },
    flaws: "None.",
  },
  {
    seed: "houndstooth",
    images: ["https://images.unsplash.com/photo-1594938252461-e42450664907?w=900&h=1125&fit=crop&q=80"],
    name: "Grey Houndstooth Trousers",
    brand: "Vintage",
    gender: "men",
    category: "Bottoms",
    price: 2399,
    originalPrice: 5999,
    sizes: ["30", "32", "34"],
    condition: "Good",
    era: "80s",
    tag: null,
    description:
      "Grey and black houndstooth trousers with a pleated front and a proper high rise. The pattern is woven rather than printed, so it will not fade out of them.",
    highlights: [
      "Woven houndstooth, not printed",
      "Pleated front, high rise",
      "Side pockets sit flat",
    ],
    details: {
      "Material": "Wool blend",
      "Fit": "High rise, straight leg",
      "Colour": "Grey houndstooth",
      "Inseam": "31 in",
      "Care": "Dry clean",
    },
    flaws: "Small repair on the inside of the left pocket - invisible from outside.",
  },
  {
    seed: "broguebootsmen",
    images: ["https://images.unsplash.com/photo-1638609348722-aa2a3a67db26?w=900&h=1125&fit=crop&q=80"],
    name: "Tan Leather Brogue Boots",
    brand: "Loake",
    gender: "men",
    category: "Footwear",
    price: 6499,
    originalPrice: 16999,
    sizes: ["UK8", "UK9", "UK10"],
    condition: "Like New",
    era: "Modern",
    tag: "GRAILS",
    description:
      "Tan calf leather brogue boots with full wingtip punching and a leather sole. Barely worn - the sole still shows the maker's stamp, which wears off within a month of real use.",
    highlights: [
      "Full wingtip brogueing",
      "Goodyear welted, leather sole",
      "Maker's stamp still visible on the sole",
    ],
    details: {
      "Material": "Calf leather, leather sole",
      "Fit": "True to size",
      "Colour": "Tan",
      "Care": "Cedar trees, polish monthly",
    },
    flaws: "None worth noting - these have hardly been out.",
  },
  {
    seed: "workboots",
    images: ["https://images.unsplash.com/photo-1542838776-096d877b5aa2?w=900&h=1125&fit=crop&q=80"],
    name: "Brown Nubuck Work Boots",
    brand: "Timberland",
    gender: "men",
    category: "Footwear",
    price: 4999,
    originalPrice: 12999,
    sizes: ["UK8", "UK9", "UK10", "UK11"],
    condition: "Good",
    era: "00s",
    tag: "BESTSELLER",
    description:
      "The six-inch nubuck work boot in classic wheat brown, properly broken in. Padded collar still has its spring and the lug sole has plenty of depth left.",
    highlights: [
      "Padded collar, still supportive",
      "Deep lug sole with real tread left",
      "Rust-proof hardware throughout",
    ],
    details: {
      "Material": "Nubuck leather, rubber lug sole",
      "Fit": "Runs half a size large",
      "Colour": "Wheat brown",
      "Care": "Nubuck brush, protector spray",
    },
    flaws: "Scuffing at both toes and some darkening across the vamp - exactly what these are meant to look like.",
  },
  {
    seed: "chronowatch",
    images: ["https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=900&h=1125&fit=crop&q=80"],
    name: "Chronograph Watch",
    brand: "Fossil",
    gender: "men",
    category: "Accessories",
    price: 4299,
    originalPrice: 11499,
    sizes: ["One Size"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "A cream-dial chronograph on a dark brown leather strap, with a steel case and a rotating bezel. Running accurately on a fresh battery, and the crystal has no scratches under angled light.",
    highlights: [
      "Fresh battery, keeping good time",
      "Crystal free of scratches",
      "Original leather strap, still supple",
    ],
    details: {
      "Material": "Stainless steel case, leather strap",
      "Case": "44mm",
      "Colour": "Cream dial, brown strap",
      "Care": "Keep the strap dry",
    },
    flaws: "Light surface marks on the case back where it sat against the wrist.",
  },
  {
    seed: "leatherwatch",
    images: ["https://images.unsplash.com/photo-1557531365-e8b22d93dbd0?w=900&h=1125&fit=crop&q=80"],
    name: "Minimalist Leather-Strap Watch",
    brand: "Vintage",
    gender: "men",
    category: "Accessories",
    price: 2799,
    originalPrice: 6999,
    sizes: ["One Size"],
    condition: "Good",
    era: "Modern",
    tag: null,
    description:
      "A pared-back silver watch with a plain white dial, slim markers and a dark brown leather strap. No date window, no clutter - just the time.",
    highlights: [
      "Clean dial, no date window",
      "Slim case sits flat under a cuff",
      "Brown leather strap with a steel buckle",
    ],
    details: {
      "Material": "Steel case, leather strap",
      "Case": "38mm",
      "Colour": "White dial, brown strap",
      "Care": "Wipe the strap, avoid water",
    },
    flaws: "The strap shows fold creases where it buckles. Case and dial are clean.",
  },
  {
    seed: "leatherbelt",
    images: ["https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=900&h=1125&fit=crop&q=80"],
    name: "Brown Leather Belt",
    brand: "Vintage",
    gender: "men",
    category: "Accessories",
    price: 1099,
    originalPrice: 2799,
    sizes: ["32", "34", "36"],
    condition: "Good",
    era: "Modern",
    tag: null,
    description:
      "A thick tan leather belt with a brushed silver buckle and a row of punched holes. Full-grain, so it has darkened where it bends and will keep doing so.",
    highlights: [
      "Full-grain leather, not bonded",
      "Brushed silver buckle",
      "Already broken in at the fold",
    ],
    details: {
      "Material": "Full-grain leather",
      "Width": "35mm",
      "Colour": "Tan brown",
      "Care": "Condition occasionally",
    },
    flaws: "Creasing at the buckle end and slight darkening around the most-used hole.",
  },
  {
    seed: "rustbeanie",
    images: ["https://images.unsplash.com/photo-1638491066547-c0e5427a4e4b?w=900&h=1125&fit=crop&q=80"],
    name: "Rust Ribbed Beanie",
    brand: "Carhartt",
    gender: "men",
    category: "Accessories",
    price: 899,
    originalPrice: 2199,
    sizes: ["One Size"],
    condition: "Like New",
    era: "Modern",
    tag: null,
    description:
      "A burnt-orange ribbed beanie with a folded cuff. Stretches to fit without going slack, and the colour is far richer in person than it photographs.",
    highlights: [
      "Deep rib with a folded cuff",
      "Stretches without losing shape",
      "Warm without being bulky",
    ],
    details: {
      "Material": "Acrylic rib knit",
      "Fit": "One size, stretches",
      "Colour": "Rust orange",
      "Care": "Hand wash, dry flat",
    },
    flaws: "None.",
  },
]

// Reviewer pool. Enough names to cover the largest review count (71) since the
// schema allows one review per user per product.
export const REVIEWER_NAMES = [
  "Priya R.", "Marcus T.", "Aisha K.", "Devin L.", "Sana M.", "Joel B.",
  "Nadia F.", "Tomas V.", "Ellie W.", "Rohan D.", "Mei L.", "Carter J.",
  "Zoe H.", "Ibrahim A.", "Lucia P.", "Ben O.", "Harriet S.", "Kwame N.",
  "Freya G.", "Diego M.", "Anouk V.", "Tara S.", "Noah C.", "Yuki T.",
  "Simone A.", "Raf E.", "Bea L.", "Omar H.", "Clara Z.", "Finn M.",
  "Isla B.", "Hugo P.", "Nina K.", "Theo R.", "Amara O.", "Louis D.",
  "Sofia G.", "Kai W.", "Elena V.", "Jonah S.", "Ruby T.", "Andre L.",
  "Maya J.", "Pierre C.", "Leah N.", "Sam K.", "Divya P.", "Otto H.",
  "Greta M.", "Zayn A.", "Iris F.", "Bruno S.", "Talia R.", "Emre Y.",
  "Norah B.", "Felix W.", "Lena D.", "Arjun M.", "Cleo T.", "Milo G.",
  "Sadie H.", "Nico B.", "Wren L.", "Kofi A.", "Juno P.", "Rosa M.",
  "Idris K.", "Vera S.", "Casper N.", "Lila W.", "Hana O.", "Enzo R.",
  "Marta C.", "Dev P.", "Astrid L.", "Rio F.", "Selin K.", "Jonas E.",
  "Bela T.", "Quinn A.",
]

// Review copy grouped by star rating, so the wording always matches the score.
export const REVIEW_CONTENT = {
  5: [
    "Arrived faster than expected and the condition notes were completely accurate. No surprises at all, which is rare buying secondhand online.",
    "The photos genuinely undersell it. Fabric feels substantial and there's none of that musty charity-shop smell — clearly actually cleaned before shipping.",
    "I've been looking for this exact piece for about two years. Fit is spot on against the measurements listed, and it came steamed and folded properly.",
    "Second thing I've bought here and the quality has been consistent both times. The measurements in the listing were accurate to within about half an inch.",
    "Really well packaged and the condition grading is honest. Would happily buy from them again without thinking about it.",
  ],
  4: [
    "Really pleased with it. Only reason it's not five stars is that it runs a bit bigger than I expected — check the flat measurements rather than the size label.",
    "Condition is as described and the fabric is lovely. Took about a week longer to arrive than I hoped, but worth the wait.",
    "Great quality for the price. There's a tiny mark that wasn't obvious in the photos, though it's genuinely not noticeable when worn.",
    "Love the piece itself. The colour is slightly deeper in person than on screen — better, in my opinion, but worth knowing.",
    "Exactly the era and cut I wanted. Knocked one star off only because I'd have liked a couple more detail photos before buying.",
  ],
  3: [
    "It's fine. The condition is accurate but the fit was tighter across the shoulders than the measurements suggested, so it doesn't get worn much.",
    "Reasonable for what I paid. There's more wear on it than 'good condition' implied to me, though nothing that stops me wearing it.",
    "Nice piece, slow delivery. Took nearly three weeks to arrive and there wasn't much in the way of updates in between.",
    "The fabric is nicer than I expected but the colour is noticeably more washed out than in the listing photos.",
  ],
  2: [
    "The listing said the hem was intact but there was some fraying that I hadn't spotted. Returns were handled politely, to be fair.",
    "Came through much smaller than the measurements indicated. It's a lovely piece, just not one I can actually wear.",
  ],
  1: [
    "Arrived with a hole near the seam that wasn't mentioned anywhere in the condition notes. Disappointing for the price.",
    "Nothing like the photos in terms of colour, and it took a month to turn up. Refund came through eventually.",
  ],
}
