// Catalog content for the seed. Kept separate from seed.js so the copy is easy to
// edit without touching the seeding logic.

export const CATEGORIES = [
  "Jackets",
  "Denim",
  "Tops",
  "Dresses",
  "Bottoms",
  "Footwear",
  "Accessories",
]

// Each listing is one physical garment, so the gallery is the set of shots our team
// takes of that single piece.
export const IMAGE_ANGLES = ["", "-back", "-detail", "-worn"]

export const PRODUCTS = [
  {
    seed: "windbreaker",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/windbreaker-front.jpg"],
    name: "Y2K Windbreaker",
    brand: "Nike ACG",
    category: "Jackets",
    price: 3499,
    originalPrice: 9999,
    sizes: ["S", "M", "L"],
    condition: "Like New",
    era: "Y2K",
    tag: "RARE FIND",
    rating: 4.8,
    reviewCount: 32,
    description:
      "A proper early-2000s ACG shell in the colourway everyone is hunting for. Lightweight ripstop with a packable hood, elasticated cuffs and the boxy cut that makes it sit right over a hoodie. Found in a Rotterdam warehouse lot and barely worn — the tags were still in the pocket.",
    highlights: [
      "Packable hood that tucks into the collar",
      "Water-repellent ripstop, taped seams intact",
      "Boxy Y2K cut — sizes up well for a layered look",
    ],
    details: {
      Material: "100% ripstop nylon, mesh lining",
      Fit: "Boxy / oversized",
      Colour: "Slate grey with volt trim",
      "Chest (flat)": '23" on size M',
      "Length (back)": '27" on size M',
      Care: "Cold machine wash, hang dry, no iron",
    },
    flaws: "None to note — closest thing to deadstock we've had in months.",
  },
  {
    seed: "carpenterjeans",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/carpenterjeans-front.jpg"],
    name: "Baggy Carpenter Denim",
    brand: "Dickies",
    category: "Denim",
    price: 2999,
    originalPrice: 6999,
    sizes: ["28", "30", "32", "34"],
    condition: "Good",
    era: "90s",
    tag: "NEW DROP",
    rating: 4.6,
    reviewCount: 58,
    description:
      "Genuine 90s Dickies carpenters with the hammer loop and double knee still fully intact. Heavy 14oz denim that has softened exactly where it should — behind the knees and at the seat — without going thin anywhere. Workwear that already did its work.",
    highlights: [
      "Original hammer loop and ruler pocket",
      "14oz denim, broken in but nowhere near worn through",
      "True 90s baggy leg — stacks over boots",
    ],
    details: {
      Material: "100% cotton, 14oz denim",
      Fit: "Relaxed / baggy straight leg",
      Colour: "Mid indigo, natural fade",
      Inseam: '32"',
      "Rise (front)": '12"',
      Care: "Cold wash inside out, line dry",
    },
    flaws: "Light fraying at the left hem and honest fading at the seat. No holes.",
  },
  {
    seed: "graphictee",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/graphictee-front.jpg"],
    name: "Cropped Graphic Tee",
    brand: "Vintage Band Tee",
    category: "Tops",
    price: 1799,
    originalPrice: 3799,
    sizes: ["XS", "S", "M"],
    condition: "Good",
    era: "2000s",
    tag: "ONE OF ONE",
    rating: 4.7,
    reviewCount: 41,
    description:
      "An original tour tee that a previous owner cropped by hand somewhere along the way — the raw edge has rolled and softened into something you genuinely can't buy new. Print is cracked in that way reproductions always fail to fake.",
    highlights: [
      "Hand-cropped raw hem, already rolled and settled",
      "Original screen print with authentic cracking",
      "Single-stitch sleeves — a real period detail",
    ],
    details: {
      Material: "100% cotton jersey, lightweight",
      Fit: "Cropped, close through the body",
      Colour: "Washed black",
      "Chest (flat)": '18" on size S',
      "Length (front)": '16" on size S',
      Care: "Cold wash inside out, hang dry — protect the print",
    },
    flaws: "Print cracking throughout (part of the appeal) and a faint mark near the left hem.",
  },
  {
    seed: "slipdress",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/slipdress-front.webp"],
    name: "Slip Satin Mini Dress",
    brand: "Bebe",
    category: "Dresses",
    price: 2299,
    originalPrice: 5799,
    sizes: ["XS", "S", "M", "L"],
    condition: "Like New",
    era: "Y2K",
    tag: "TRENDING",
    rating: 4.9,
    reviewCount: 27,
    description:
      "The exact bias-cut Bebe slip that keeps resurfacing on everyone's moodboard. Adjustable straps, a proper bias cut that skims rather than clings, and satin that still has its full sheen. Someone bought this for one night out and hung it up ever since.",
    highlights: [
      "True bias cut — hangs instead of gripping",
      "Adjustable straps with original sliders",
      "Satin sheen fully intact, no dulling",
    ],
    details: {
      Material: "Polyester satin, unlined",
      Fit: "Bias cut, skims the body",
      Colour: "Champagne",
      "Bust (flat)": '16.5" on size S',
      Length: '34" shoulder to hem',
      Care: "Hand wash cold or dry clean, hang to dry",
    },
    flaws: "None found. Straps, seams and hem all sound.",
  },
  {
    seed: "flannel",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/flannel-front.jpg"],
    name: "Oversized Flannel Shirt",
    brand: "Carhartt",
    category: "Tops",
    price: 1999,
    originalPrice: 4999,
    sizes: ["M", "L", "XL"],
    condition: "Good",
    era: "90s",
    tag: null,
    rating: 4.5,
    reviewCount: 19,
    description:
      "Heavyweight Carhartt flannel that has been washed enough times to go genuinely soft without losing any structure. Works as a shirt, works better as a light jacket over a tee. The kind of piece that quietly becomes the one you reach for.",
    highlights: [
      "Heavyweight brushed cotton, washed soft",
      "All original branded buttons present",
      "Roomy enough to layer over a hoodie",
    ],
    details: {
      Material: "100% brushed cotton flannel",
      Fit: "Oversized, drop shoulder",
      Colour: "Rust and forest plaid",
      "Chest (flat)": '25" on size L',
      "Length (back)": '30" on size L',
      Care: "Warm machine wash, tumble low",
    },
    flaws: "Slight collar fade and one replaced button at the cuff — matched closely.",
  },
  {
    seed: "platformsneakers",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/platformsneakers-front.jpg"],
    name: "Chunky Platform Sneakers",
    brand: "Buffalo",
    category: "Footwear",
    price: 4499,
    originalPrice: 11499,
    sizes: ["6", "7", "8", "9"],
    condition: "Like New",
    era: "Y2K",
    tag: "RARE FIND",
    rating: 4.8,
    reviewCount: 63,
    description:
      "The Buffalo platform in its original chunky silhouette — the one every current brand is busy reissuing at four times the price. Soles are clean, uppers hold their shape, and there is no yellowing anywhere on the midsole.",
    highlights: [
      'Original 2" platform sole, no compression',
      "Midsole still white — zero yellowing",
      "Barely-there tread wear",
    ],
    details: {
      Material: "Leather upper, rubber platform sole",
      Fit: "True to size, roomy toe box",
      Colour: "White with silver panel",
      "Platform height": '2"',
      Closure: "Lace-up, original laces",
      Care: "Wipe clean, avoid soaking the midsole",
    },
    flaws: "Faint scuff on the right toe cap, only visible up close.",
  },
  {
    seed: "trenchcoat",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/trenchcoat-front.jpg"],
    name: "Leather Trench Coat",
    brand: "Vintage",
    category: "Jackets",
    price: 5499,
    originalPrice: 14999,
    sizes: ["S", "M", "L"],
    condition: "Good",
    era: "80s",
    tag: "ONE OF ONE",
    rating: 4.9,
    reviewCount: 14,
    description:
      "Full-length 80s leather trench with the shoulder line and sweeping hem that define the era. The leather has developed a genuine patina — soft, slightly uneven, warm in tone. Heavy in the way real leather should be. This is the only one we have.",
    highlights: [
      "Full-grain leather with 40 years of real patina",
      "Belted waist with original buckle",
      "Fully lined, all seams sound",
    ],
    details: {
      Material: "Full-grain leather, satin lining",
      Fit: "Straight, dramatic shoulder",
      Colour: "Oxblood brown",
      "Chest (flat)": '22" on size M',
      Length: '48" shoulder to hem',
      Care: "Leather conditioner twice a year, never machine wash",
    },
    flaws:
      "Patina and softening throughout, one small scuff at the right elbow. Lining intact.",
  },
  {
    seed: "cargopants",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/cargopants-front.webp"],
    name: "Low-Rise Cargo Pants",
    brand: "Dickies",
    category: "Bottoms",
    price: 2799,
    originalPrice: 6299,
    sizes: ["S", "M", "L"],
    condition: "Good",
    era: "Y2K",
    tag: "NEW DROP",
    rating: 4.6,
    reviewCount: 48,
    description:
      "Low-rise cargos with the deep side pockets and slightly flared ankle that put them firmly in the early 2000s. Cotton twill that has gone soft with wear but still holds a shape. Every pocket, snap and drawcord works.",
    highlights: [
      "Six functional pockets, all snaps working",
      "Adjustable ankle drawcords intact",
      "True low rise — sits on the hip",
    ],
    details: {
      Material: "Cotton twill with a little stretch",
      Fit: "Low rise, relaxed leg",
      Colour: "Khaki",
      Inseam: '31"',
      "Rise (front)": '8"',
      Care: "Cold machine wash, tumble low",
    },
    flaws: "General softening and a faint mark on the right thigh pocket.",
  },
  {
    seed: "truckerjacket",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/truckerjacket-front.jpg"],
    name: "Denim Trucker Jacket",
    brand: "Levi's",
    category: "Jackets",
    price: 3799,
    originalPrice: 7999,
    sizes: ["S", "M", "L", "XL"],
    condition: "Like New",
    era: "90s",
    tag: "TRENDING",
    rating: 4.7,
    reviewCount: 71,
    description:
      "The Levi's trucker, which is to say the jacket every other denim jacket is copying. This one is a 90s make with the red tab intact and a light, even fade that you simply cannot rush. Goes with everything already in your wardrobe.",
    highlights: [
      "Original red tab and branded shank buttons",
      "Even, natural fade — no artificial distressing",
      "Classic cropped trucker length",
    ],
    details: {
      Material: "100% cotton denim, 12oz",
      Fit: "Regular, cropped at the waist",
      Colour: "Mid stonewash",
      "Chest (flat)": '21" on size M',
      "Length (back)": '24" on size M',
      Care: "Cold wash inside out, line dry",
    },
    flaws: "Nothing structural. Gentle whiskering at the cuffs and a soft collar.",
  },
  {
    seed: "pleatedskirt",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/pleatedskirt-front.png"],
    name: "Pleated Mini Skirt",
    brand: "Vintage Plaid",
    category: "Bottoms",
    price: 1699,
    originalPrice: 3999,
    sizes: ["XS", "S", "M"],
    condition: "Good",
    era: "90s",
    tag: null,
    rating: 4.4,
    reviewCount: 22,
    description:
      "Proper pressed-pleat plaid mini with a side zip and a wool-blend weight that makes the pleats actually hold. Not the flimsy polyester version — this one swings correctly when you walk.",
    highlights: [
      "Wool blend, pleats hold their press",
      "Concealed side zip with hook and eye",
      "Fully lined so it never clings",
    ],
    details: {
      Material: "Wool blend, polyester lining",
      Fit: "High waist, A-line",
      Colour: "Green and navy plaid",
      "Waist (flat)": '13" on size S',
      Length: '15" from waist',
      Care: "Dry clean, cool iron on the reverse",
    },
    flaws: "Two pleats need re-pressing after shipping. Lining has a small repaired seam.",
  },
  {
    seed: "beadednecklace",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/beadednecklace-front.webp"],
    name: "Beaded Statement Necklace",
    brand: "Handmade Vintage",
    category: "Accessories",
    price: 1199,
    originalPrice: 2499,
    sizes: ["One Size"],
    condition: "Like New",
    era: "Y2K",
    tag: "ONE OF ONE",
    rating: 4.9,
    reviewCount: 9,
    description:
      "Hand-strung glass beads in a graduated pattern that someone clearly took real time over. Restrung by us on fresh wire so it will not scatter across your floor. Genuinely a single object — there is no second one of these anywhere.",
    highlights: [
      "Hand-strung glass beads, graduated pattern",
      "Professionally restrung on new wire",
      "Lobster clasp replaced with a new one",
    ],
    details: {
      Material: "Glass beads, stainless wire and clasp",
      Length: '18" with a 2" extender',
      Colour: "Amber, jade and clear",
      "Bead size": "6-12mm graduated",
      Care: "Store flat, keep away from perfume",
    },
    flaws: "None — restrung and checked bead by bead before listing.",
  },
  {
    seed: "buckethat",
    images: ["https://0aiajnfg6uwj498l.public.blob.vercel-storage.com/products/buckethat-front.jpg"],
    name: "Retro Bucket Hat",
    brand: "Kangol",
    category: "Accessories",
    price: 1349,
    originalPrice: 2899,
    sizes: ["One Size"],
    condition: "Good",
    era: "90s",
    tag: null,
    rating: 4.5,
    reviewCount: 26,
    description:
      "Kangol bucket in the towelling fabric that made them famous, with the kangaroo logo still crisp on the back. Brim holds its shape and the interior band is clean. Reliable, unfussy, works with everything.",
    highlights: [
      "Original embroidered kangaroo logo",
      "Towelling fabric, brim holds its shape",
      "Interior sweatband clean and intact",
    ],
    details: {
      Material: "Cotton blend towelling",
      Fit: 'One size, 22-23" circumference',
      Colour: "Faded navy",
      "Brim width": '2"',
      Care: "Hand wash cold, air dry on a form",
    },
    flaws: "Very light fading on the crown from sun. Nothing structural.",
  },
]

// Reviewer pool. Enough names to cover the largest review count (71) since the
// schema allows one review per user per product.
export const REVIEWER_NAMES = [
  "Priya R.", "Marcus T.", "Aisha K.", "Devin L.", "Sana M.", "Joel B.",
  "Nadia F.", "Tomas V.", "Ellie W.", "Rohan D.", "Mei L.", "Carter J.",
  "Zoe H.", "Ibrahim A.", "Lucia P.", "Ben O.", "Harriet S.", "Kwame N.",
  "Freya G.", "Diego M.", "Anouk V.", "Tara S.", "Noah C.", "Yuki T.",
  "Simone A.", "Raf E.", "Bea L.", "Omar H.", "Clara Z.", "Finn M.",
  "Isla B.", "Hugo P.", "Nina K.", "Theo R.", "Amara O.", "Louis D.",
  "Sofia G.", "Kai W.", "Elena V.", "Jonah S.", "Ruby T.", "Andre L.",
  "Maya J.", "Pierre C.", "Leah N.", "Sam K.", "Divya P.", "Otto H.",
  "Greta M.", "Zayn A.", "Iris F.", "Bruno S.", "Talia R.", "Emre Y.",
  "Norah B.", "Felix W.", "Lena D.", "Arjun M.", "Cleo T.", "Milo G.",
  "Sadie H.", "Nico B.", "Wren L.", "Kofi A.", "Juno P.", "Rosa M.",
  "Idris K.", "Vera S.", "Casper N.", "Lila W.", "Hana O.", "Enzo R.",
  "Marta C.", "Dev P.", "Astrid L.", "Rio F.", "Selin K.", "Jonas E.",
  "Bela T.", "Quinn A.",
]

// Review copy grouped by star rating, so the wording always matches the score.
export const REVIEW_CONTENT = {
  5: [
    "Arrived faster than expected and the condition notes were completely accurate. No surprises at all, which is rare buying secondhand online.",
    "The photos genuinely undersell it. Fabric feels substantial and there's none of that musty charity-shop smell — clearly actually cleaned before shipping.",
    "I've been looking for this exact piece for about two years. Fit is spot on against the measurements listed, and it came steamed and folded properly.",
    "Second thing I've bought here and the quality has been consistent both times. The measurements in the listing were accurate to within about half an inch.",
    "Really well packaged and the condition grading is honest. Would happily buy from them again without thinking about it.",
  ],
  4: [
    "Really pleased with it. Only reason it's not five stars is that it runs a bit bigger than I expected — check the flat measurements rather than the size label.",
    "Condition is as described and the fabric is lovely. Took about a week longer to arrive than I hoped, but worth the wait.",
    "Great quality for the price. There's a tiny mark that wasn't obvious in the photos, though it's genuinely not noticeable when worn.",
    "Love the piece itself. The colour is slightly deeper in person than on screen — better, in my opinion, but worth knowing.",
    "Exactly the era and cut I wanted. Knocked one star off only because I'd have liked a couple more detail photos before buying.",
  ],
  3: [
    "It's fine. The condition is accurate but the fit was tighter across the shoulders than the measurements suggested, so it doesn't get worn much.",
    "Reasonable for what I paid. There's more wear on it than 'good condition' implied to me, though nothing that stops me wearing it.",
    "Nice piece, slow delivery. Took nearly three weeks to arrive and there wasn't much in the way of updates in between.",
    "The fabric is nicer than I expected but the colour is noticeably more washed out than in the listing photos.",
  ],
  2: [
    "The listing said the hem was intact but there was some fraying that I hadn't spotted. Returns were handled politely, to be fair.",
    "Came through much smaller than the measurements indicated. It's a lovely piece, just not one I can actually wear.",
  ],
  1: [
    "Arrived with a hole near the seam that wasn't mentioned anywhere in the condition notes. Disappointing for the price.",
    "Nothing like the photos in terms of colour, and it took a month to turn up. Refund came through eventually.",
  ],
}
